# Buuld the React application
FROM node:18-alpine AS build

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application frontend code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight web server to serve the built application
FROM nginx:stable-alpine

# Copy the built application from the previous stage
COPY --from=build /app/frontend/dist /usr/share/nginx/html

# Add custom Nginx config with SPA fallback
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the actual Nginx port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
